#port 8081로 설정
server:
  port: 8081

#oracle 연동
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.driver.OracleDriver
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/static/dist

#log레벨 설정 / 기본은 info
logging:
  level:
    root: info
#    root: warn

#mybatis 경로 설정
mybatis:
  mapper-locations: classpath*:**/query/*Mapper.xml
  config-location: classpath:mybatis-config.xml
